### ISSUE TITLE
Mappings from R to database types

### ISSUE THREAD

**Issue by richfitz** [ropensci/nodbi#1]
Obvious first candidate for support is `data.frame`, but could use some support for non-`data.frame` like indexable structures (i.e., lists) and nested lists (access like graphs).

**Comment by sckott** [comment]
So we have a plain english version of what each DB is doing, in the language of each DB

### data.frame's

* couchdb: for each data.frame, create new `database`, store each row in separate `document`
* etcd: for each data.frame, create new `directory`, store each row in separate `key`
* elasticsearch: for each data.frame, create new `index`, with `type` of same name, store each row in separate `document`

**Comment by rfhb** [comment]
Covered by documentation in package functions and at https://github.com/ropensci/nodbi#database-connections.
