### ISSUE TITLE
Proposal: rename to nodbi

### ISSUE THREAD

**Issue by richfitz** [ropensci/nodbi#11]
The "nosql" bit is probably more unifying than "document"?

**Comment by sckott** [comment]
sounds fine to me

@jeroenooms  ?

**Comment by jeroenooms** [comment]
Yes I like it.

**Comment by jeroenooms** [comment]
The term 'document' always confuses people, it's kind of a weird name for a data structure.

**Comment by richfitz** [comment]
Great.  At the same time, let's convert all `docid` arguments to `key` (we currently use both; compare get.R and delete.R).

**Comment by sckott** [comment]
sounds good, i'll change the repo name
