### ISSUE TITLE
Update operations

### ISSUE THREAD

**Issue by wolkym** [ropensci/nodbi#12]
Is there update operation avaliable?
e.g. I change one row in the `data.frame` after  `docdb_get` and would like to insert difference?

**Comment by sckott** [comment]
No, we don't have updates, but we can work on that.

**Comment by sckott** [comment]
@cronacronis Okay, started this. Only with Couchdb for now.  Try if you like. See examples at https://github.com/ropensci/nodbi/blob/master/R/update.R#L9-L17

I'll work on adding other DBs

**Comment by sckott** [comment]
works for couchdb for now, will open a new issue to fill out remainder
