### ISSUE TITLE
Error: 'cushions' is not an exported object from 'namespace:sofa'

### ISSUE THREAD

**Issue by JARS3N** [ropensci/nodbi#13]
Maybe I'm missing something or doing something wrong but I don't see any thing as 'cushions' in the sofa pakcage, I do see an object 'Cushion'. This was while trying to run the function src_couchdb()

**Comment by sckott** [comment]
Hi - as you can see https://github.com/ropensci/nodbi/commits/master it's been a while since we've worked on this - Some things are broken now, sorry 😿 

I'll update the package to at least fix any broken things 🕥

**Comment by sckott** [comment]
@JARS3N reinstall `devtools::install_github("ropensci/nodbi")` and try again

couch stuff should work now - though still need to fix other db interfaces
