### ISSUE TITLE
Can't get redux to install on Travis

### ISSUE THREAD

**Issue by sckott** [ropensci/nodbi#15]
any thoughts @richfitz ?

**Comment by sckott** [comment]
here's the last travis build I tried https://travis-ci.org/ropensci/nodbi/builds/377800299#L1402-L1417 including redux installation. libhiredis-dev installs fine, but then redux doesn't seem to recognize it. 

everything goes smoothly on my mac. 

i have the same problem on a fresh linux box that travis has

**Comment by rfhb** [comment]
Support for redux has been removed in 2021 from nodbi; the document concept did not map well.
