### ISSUE TITLE
Databases

### ISSUE THREAD

**Issue by sckott** [ropensci/nodbi#2]
Last updated on 2022-11-03 (@rfhb): 

- [x] Mongodb  - @jeroen 
- [x] CouchDB - @sckott  
- [x] Elasticsearch - @sckott
- [x] SQLite  - @rfhb (from 0.3.0)
- [x] PostgreSQL  - @rfhb (from 0.6.0)
- [x] Duckdb - @rfhb (from 0.9.0)

Previously considered: 
- [ ] Redis - richfitz (removed 2021, does not work on docs)
- [ ] Etcd - rich 
- [ ] Riak - sckott (pulling out for now - not done yet)
- [ ] OrientDB - 
- [ ] ArangoDB - 
- [ ] RethinkDB https://github.com/mbq/rethinker
- [ ] BerkeleyDB https://github.com/hrbrmstr/RBerkeley / https://github.com/richfitz/storr.bdb 
- [ ]  ~~Foundationdb~~ ha! nevermind, :apple: happened

**Comment by sandys** [comment]
please support postgresql jsonb - its one of the most extensively used document database now. Redshift is entirely based on this.

**Comment by sckott** [comment]
thanks for the suggestion @sandys - we'll look into it

**Comment by jeroenooms** [comment]
@sandys what do you mean? postgresql is not part of the nodbi suite? And it is already supported in [Rpostgres](https://github.com/rstats-db/RPostgres) ?

**Comment by sandys** [comment]
Hi jeroen
I did not mean as a connection mechanism (of which you just fixed a bug
yesterday), but of the usage paradigm.

For example the mental model of mongodb, etcd is along key values...
Postgresql jsonb is incredible and rivals mongo in speed, yet gives ACID...
But most of the connectors still use it as a relational db.

This request was to enable a nosql use model for postgresql jsonb.

**Comment by sckott** [comment]
@jeroenooms i think it makes sense here, do you not?

**Comment by sandys** [comment]
just FYI - these are the operators and types that are supported by
Postgresql in its NOSQL jsonb schema

http://www.postgresql.org/docs/9.5/static/datatype-json.html
http://www.postgresql.org/docs/9.4/static/functions-json.html

On Thu, Feb 4, 2016 at 11:39 PM, Scott Chamberlain <notifications@github.com

**Comment by jeroenooms** [comment]
I'm not very familiar with `jsonb`. Can you elaborate @sandys ? Afaik, the `jsonb` is a field within a table, not an entire table or collectino. What would a `nodbi` interface to a `jsonb` value look like?

**Comment by rfhb** [comment]
`nodbi` now also works with PostgreSQL, using `jsonb` functions and the `RPostgres` connector package; the API and the return values are the same across backends. For a benchmark, see https://github.com/ropensci/nodbi#benchmark.

**Comment by sckott** [comment]
nice work

**Comment by rfhb** [comment]
Added: support for using DuckDB (R package duckdb >= 0.6.0) as backend

**Comment by rfhb** [comment]
Closing as mostly covered at https://github.com/ropensci/nodbi#database-connections; a new development roadmap remains to be drafted.
