### ISSUE TITLE
Function to run raw commands

### ISSUE THREAD

**Issue by GitHunter0** [ropensci/nodbi#43]
Hi folks, first let me say `nodbi` is a really great project that I hope keeps flourishing.

Is there a way to run raw database commands (for operations that `nodbi` currently does not implement), analogous to [mongolite's run()](https://jeroen.github.io/mongolite/server-tools.html#running-commands)? 

I have also 2 aside questions if I may:
(1) How can I disconnect from the database? I could not find in `nodbi` a command like mongolite's `$disconnect()`
(2) Since in commands like `docdb_query(key = "...")` we cannot change the `key` (we would receive a warning message), why make mandatory to provide it every time? In mongolite, for example, `$find()` just requires the `query` paramater.

Thank you

**Comment by rfhb** [comment]
Hi and many thanks, sorry, could not reply earlier. 

Are you looking to run a few specific commands across all backends? Which commands are you thinking of? If the command would not have analogous or corresponding commands across the backends, it may be easier to just call the backend-specific function, for example: 

```
dbc <- nodbi::src_mongo(
    db = "my_db", 
    collection = "my_coll")

mongolite::mongo(
  collection = dbc$collection,
  db = dbc$db,
  url = dbc$url)$run(command = '{"ping": 1}')
```

In analogy, the other backends can be used with a `nodbi` connection object. 

Re (1): manually disconnecting is not necessary for several (e.g. PostgreSQL, Mongo) if not all backends. A method could be added but `R`'s garbage collection should be sufficient. Did you run into any problems? 

Re (2): this is for consistency of the main parameters across `nodbi` functions. I will review if simplification e.g. for `nodbi::doc_query()` would be a good gain. 

Thanks again
