### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by richfitz** [ropensci/nodbi#8]
@sckott has run some benchmarks for different key/value stores: it'd be good to revive these and run them for the low-level things that we're trying: cost of serialising a dataframe by row to different backends, etc.  That'd help us work out which database is going to be most useful and for users and developers to work out what database would best suit their application.

**Comment by jeroenooms** [comment]
That sounds a bit premature though; speed of an early implementation might not be representative for the database. For example I implemented a 10x speedup today.

**Comment by richfitz** [comment]
Sweet.  However, I think that getting some measure of "par" up early would be nice and help motivate other 10x speedups.  But it can also wait, too.

**Comment by jeroenooms** [comment]
I think it's more important to make things work on all platforms and come up with a nice interface before worrying about performance. There is all kind of crazy stuff that you can do to optimize, but remember: premature optimization is the root of all evil :)

**Comment by sckott** [comment]
Definitely interested in benchmarks, but does make sense to focus on the user interface first

**Comment by rfhb** [comment]
@richfitz @sckott @jeroen `nodbi`benchmark added to README, using local CouchDB, Elasticsearch, MongoDB, SQLite and PostgreSQL; please see https://github.com/ropensci/nodbi#benchmark.
