### ISSUE TITLE
rrlite example broken

### ISSUE THREAD

**Issue by jeroenooms** [ropensci/nodbi#9]
```r
> src <- src_rrlite()
> docdb_create(src, "mtcars", mtcars)
Error: 'to_redis' is not an exported object from 'namespace:rrlite'
> docdb_get(src, "mtcars")
Error: 'from_redis' is not an exported object from 'namespace:rrlite'
```

@richfitz

**Comment by richfitz** [comment]
Thanks; moved a bunch of stuff around and that's in RedisAPI now. Will fix tomorrow.

**Comment by jeroenooms** [comment]
Okay, no hurry, just wanted to do some benchmarking.

**Comment by richfitz** [comment]
Got most of this done today, so it *is* moving, if slowly...

**Comment by sckott** [comment]
:turtle:

**Comment by jennybc** [comment]
But you know what they say about the :turtle: and the :rabbit:.

**Comment by sckott** [comment]
hmm, was that :turtle: has a :beer: w/ :rabbit: ?

**Comment by richfitz** [comment]
This is fixed but I've not updated the Rmd because I don't have all the other dbs installed. @sckott would you mind?

**Comment by sckott** [comment]
updated readme, i assume this can be closed :question:
